version: '3.7'
services:
  chanakya:
    build:
      dockerfile: Dockerfile
      context: .
    image : chanakya
    container_name: chanakya-prod-container
    env_file:
      - .env

    network_mode: host