questions =[{'difficulty': 'Medium',
  'en_text': 'Inme se kaun sa letter sequenece mein nahi tha?"',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'D', 'hi_text': 'D'},
              {'correct': False, 'en_text': 'F', 'hi_text': 'F'},
              {'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': True, 'en_text': 'P', 'hi_text': 'P'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mOZHJH/19.png' "
             "height='350px'></center><br/>isme se kaunsi image aapne memorize "
             'ki thi ?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': False, 'en_text': 'A', 'hi_text': 'A'},
              {'correct': True, 'en_text': 'C', 'hi_text': 'C'},
              {'correct': False, 'en_text': 'D', 'hi_text': 'D'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': 'Kaun se word ka color blue tha?"',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'red', 'hi_text': 'red'},
              {'correct': True, 'en_text': 'orange', 'hi_text': 'orange'},
              {'correct': False, 'en_text': 'black', 'hi_text': 'black'},
              {'correct': False, 'en_text': 'green', 'hi_text': 'green'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/gqfk5x/p27.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/gc5eXc/p10.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/n4ppXc/p18.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/h98GCc/p29.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mFHnJH/p30.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/jFW8Qx/p11.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/n9pHJH/p4.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/nfeHJH/p7.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/dEsXkx/p33.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/kiOuyH/p21.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/hL6gdH/p37.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/hsEOsc/p34.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/cNFJQx/p38.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/f8b8Qx/p3.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/iUgQ5x/p31.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/hCkDsc/p1.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/eDWmCc/p2.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/jOnnJH/p36.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/gxbQ5x/p28.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/dxMKXc/p8.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/exAk5x/p35.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/kPawCc/p24.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/dfrskx/p23.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/eL0eXc/p17.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/b2rEyH/p25.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mUFk5x/p32.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/enpv5x/p13.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/b7BgdH/p19.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/cdiYsc/p6.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/cRxXkx/p26.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/j5izXc/p14.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/gEVUXc/p39.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/kTyNkx/p9.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/c7aUXc/p20.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': True,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/coq2kx/p5.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'},
              {'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mLkrdH/p12.png' "
             "height='350px'></center><br/>choose right or wrong",
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': 'गलत / INCORRECT',
               'hi_text': 'गलत / INCORRECT'},
              {'correct': True,
               'en_text': 'सही / CORRECT',
               'hi_text': 'सही / CORRECT'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Medium',
  'en_text': "<center><img src='https://image.ibb.co/g1tBdH/11.png' "
             "height='350px'></center><br/>Question mark ki jagah par sahi "
             'figure choose kijiye',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False,
               'en_text': "<img src='https://image.ibb.co/i7eTQx/11C.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/i7eTQx/11C.png' "
                          "class='option-image'>"},
              {'correct': True,
               'en_text': "<img src='https://image.ibb.co/bUCF5x/11A.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/bUCF5x/11A.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/m6RWdH/11D.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/m6RWdH/11D.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/diMKXc/11B.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/diMKXc/11B.png' "
                          "class='option-image'>"}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Medium',
  'en_text': "<center><img src='https://image.ibb.co/dGqPyH/14.png' "
             "height='350px'></center> <br> Di gyi image me total kitne boxes "
             'hai?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': True, 'en_text': 'E', 'hi_text': 'E'},
              {'correct': False, 'en_text': 'C', 'hi_text': 'C'},
              {'correct': False, 'en_text': 'A', 'hi_text': 'A'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/mGK6Cc/10.png' "
             "height='350px'></center><br/>Question mark ki jagah par sahi "
             'figure choose kijiye',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False,
               'en_text': "<img src='https://image.ibb.co/mFr8Qx/10D.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/mFr8Qx/10D.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/mf8oQx/10B.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/mf8oQx/10B.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/fSrWdH/10C.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/fSrWdH/10C.png' "
                          "class='option-image'>"},
              {'correct': True,
               'en_text': "<img src='https://image.ibb.co/mCXF5x/10A.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/mCXF5x/10A.png' "
                          "class='option-image'>"}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/nFBWdH/13.png' "
             "height='350px'></center> <br/>Diye hue image ka reflection kaisa "
             'hoga?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'E', 'hi_text': 'E'},
              {'correct': True, 'en_text': 'D', 'hi_text': 'D'},
              {'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': False, 'en_text': 'A', 'hi_text': 'A'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': "<center><img src='https://image.ibb.co/hGjv5x/12.png' "
             "height='350px'></center><br/>Question mark ki jagah par sahi "
             'figure choose kijiye',
  'hi_text': 'सही या गलत चुनिए',
  'options': [{'correct': False,
               'en_text': "<img src='https://image.ibb.co/fm74yH/12C.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/fm74yH/12C.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/c1v2kx/12B.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/c1v2kx/12B.png' "
                          "class='option-image'>"},
              {'correct': True,
               'en_text': "<img src='https://image.ibb.co/mfH4yH/12A.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/mfH4yH/12A.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/hqMmCc/12D.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/hqMmCc/12D.png' "
                          "class='option-image'>"}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': "<center><img src='https://image.ibb.co/kM0eXc/15.png' "
             "height='350px'></center><br/>Fold karne ke baad, ye 2D image kis "
             'box ki tarah banega? ',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'A', 'hi_text': 'A'},
              {'correct': False, 'en_text': 'B', 'hi_text': 'B'},
              {'correct': True, 'en_text': 'E', 'hi_text': 'E'},
              {'correct': False, 'en_text': 'D or C', 'hi_text': 'D or C'}],
  'topic': 'BASIC_MATH',
  'type': 'MCQ'},
 {'difficulty': 'Medium',
  'en_text': 'Cheerapunji ka temperature morning mein -14 degree celsius hota '
             'hai.<br/>Agar wahan ka temperature 7 degrees aur drop hota hai, '
             'toh Cheerapunji ka temperature kitna hai?',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': True, 'en_text': '-21', 'hi_text': '-21'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Medium',
  'en_text': "<center><img src='https://image.ibb.co/bSpjyH/8.png' "
             "height='350px'></center><br/>Shaded area poore area ka kitna "
             'percent hai?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': '35%', 'hi_text': '35%'},
              {'correct': False, 'en_text': '40%', 'hi_text': '40%'},
              {'correct': False, 'en_text': '30%', 'hi_text': '30%'},
              {'correct': True, 'en_text': '25%', 'hi_text': '25%'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Medium',
  'en_text': 'Neeche diye hue equations mein x ke liye solve karein: <br/>x = '
             'y - 6 <br/>y = 10 <br/><br/>x = ?',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': True, 'en_text': '4', 'hi_text': '4'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Easy',
  'en_text': '8(−25)16−(−25)−16<br/><br/>write your answer below',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': True, 'en_text': '8', 'hi_text': '8'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Easy',
  'en_text': 'Maan lein ki x = a/b  hai.<br/>Agar a =6 aur b=2 toh x ki value '
             'kya hai?',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': True, 'en_text': '3', 'hi_text': '3'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/hXntsc/7.png' "
             "height='350px'></center><br/>Shaded area poore area ka kitna "
             'percent hai?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': '80%', 'hi_text': '80%'},
              {'correct': False, 'en_text': '50%', 'hi_text': '50%'},
              {'correct': True, 'en_text': '70%', 'hi_text': '70%'},
              {'correct': False, 'en_text': '60%', 'hi_text': '60%'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': 'Aapke room ka temperature -17 degree Celsius hai.<br/>Aapne apne '
             'room mein room heater on kiya.<br/>Ab aapke kamre ka temperature '
             'every 5 minutes mein 3 degree celsius badh raha hai. 30 mins '
             'baad aapke room ka temperature kitna hoga?',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': True, 'en_text': '1', 'hi_text': '1'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Hard',
  'en_text': '5 ml black color aur 4 ml white color se grey color banta hai. '
             'Niche diye hue kis color combination se grey color banega? ',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False,
               'en_text': '30ml black, 20 ml white',
               'hi_text': '30ml black, 20 ml white'},
              {'correct': True,
               'en_text': '30ml black, 24ml white',
               'hi_text': '30ml black, 24ml white'},
              {'correct': False,
               'en_text': '25ml black, 16ml white',
               'hi_text': '25ml black, 16ml white'},
              {'correct': False,
               'en_text': '40ml black, 30ml white',
               'hi_text': '40ml black, 30ml white'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': 'x aur y ke liye solve karein:<br/>y =    x  4<br/>y =  2x  '
             '2<br/>',
  'hi_text': 'नीचे उत्तर लिखिए',
  'options': [{'correct': False, 'en_text': '3,5', 'hi_text': '3,5'},
              {'correct': False, 'en_text': '4,2', 'hi_text': '4,2'},
              {'correct': False, 'en_text': '2,4', 'hi_text': '2,4'},
              {'correct': True, 'en_text': '2,6', 'hi_text': '2,6'}],
  'topic': 'ABSTRACT_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Medium',
  'en_text': 'Inn numbers ko dekhiye aur agla number guess kijiye:<br/>1, 8. '
             '27, 64, 125 , ?',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': True, 'en_text': '216', 'hi_text': '216'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'Integer Answer'},
 {'difficulty': 'Easy',
  'en_text': "<center><img src='https://image.ibb.co/bzGxJH/16.png' "
             "height='350px'></center><br/>Niche diye hue images mein agla "
             'image kaun sa aayega',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': False, 'en_text': 'D', 'hi_text': 'D'},
              {'correct': False, 'en_text': 'B or C', 'hi_text': 'B or C'},
              {'correct': True, 'en_text': 'A', 'hi_text': 'A'},
              {'correct': False, 'en_text': 'E', 'hi_text': 'E'}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'},
 {'difficulty': 'Hard',
  'en_text': "<center><img src='https://image.ibb.co/iUBKXc/18.png' "
             "height='350px'></center><br/>Niche diye hue images mein agla "
             'image kaun sa aayega',
  'hi_text': 'नीचे उत्तर दीजिए',
  'options': [{'correct': True,
               'en_text': "<img src='https://image.ibb.co/mprxJH/18A.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/mprxJH/18A.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/gr1a5x/18C.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/gr1a5x/18C.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/jeDBdH/18B.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/jeDBdH/18B.png' "
                          "class='option-image'>"},
              {'correct': False,
               'en_text': "<img src='https://image.ibb.co/jBrKXc/18D.png' "
                          "class='option-image'>",
               'hi_text': "<img src='https://image.ibb.co/jBrKXc/18D.png' "
                          "class='option-image'>"}],
  'topic': 'NON_VERBAL_LOGICAL_REASONING',
  'type': 'MCQ'}]


print(len(questions))
