"""empty message

Revision ID: 1a6f033e133a
Revises: 7b3263c4e659
Create Date: 2018-02-14 08:46:47.437417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a6f033e133a'
down_revision = '7b3263c4e659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('en_question_text', sa.String(length=1024), nullable=False))
    op.add_column('question', sa.Column('hi_question_text', sa.String(length=1024), nullable=False))
    op.drop_column('question', 'question_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_text', mysql.VARCHAR(length=1024), nullable=False))
    op.drop_column('question', 'hi_question_text')
    op.drop_column('question', 'en_question_text')
    # ### end Alembic commands ###
