"""empty message

Revision ID: 2f796d4ac118
Revises: aeefc293a392
Create Date: 2018-08-08 11:30:34.098710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f796d4ac118'
down_revision = 'aeefc293a392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('current_status', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('email_id', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('religion', sa.String(length=50), nullable=True))
    op.add_column('student', sa.Column('whatsapp_number', sa.String(length=13), nullable=True))
    op.drop_column('student', 'family_head')
    op.drop_column('student', 'owned_items')
    op.drop_column('student', 'housing_type')
    op.drop_column('student', 'earning_fam_members')
    op.drop_column('student', 'family_head_org_membership')
    op.drop_column('student', 'city_or_village')
    op.drop_column('student', 'family_head_other')
    op.drop_column('student', 'pin_code')
    op.drop_column('student', 'urban_family_head_prof')
    op.drop_column('student', 'family_head_income')
    op.drop_column('student', 'district')
    op.drop_column('student', 'family_head_qualification')
    op.drop_column('student', 'family_land_holding')
    op.drop_column('student', 'family_type')
    op.drop_column('student', 'rural_family_head_prof')
    op.drop_column('student', 'family_draught_animals')
    op.drop_column('student', 'tehsil')
    op.drop_column('student', 'urban_rural')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('urban_rural', mysql.ENUM('urban', 'rural'), nullable=True))
    op.add_column('student', sa.Column('tehsil', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('student', sa.Column('family_draught_animals', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('rural_family_head_prof', mysql.ENUM('unemployed', 'labourer', 'caste_related_work', 'business', 'independent_work', 'work_on_own_land', 'service'), nullable=True))
    op.add_column('student', sa.Column('family_type', mysql.ENUM('single', 'joint'), nullable=True))
    op.add_column('student', sa.Column('family_land_holding', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('family_head_qualification', mysql.ENUM('no_reading_writing', 'reading_writing', 'class_5_pass', 'class_8_pass', 'class_10_pass', 'class_12_pass', 'graduate', 'post_graduation', 'prof_degree'), nullable=True))
    op.add_column('student', sa.Column('district', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('student', sa.Column('family_head_income', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('urban_family_head_prof', mysql.ENUM('unemployed', 'no_training_jobs', 'jobs_with_training', 'high_training', 'read_write_jobs', 'routine_work', 'prof_degree_work'), nullable=True))
    op.add_column('student', sa.Column('pin_code', mysql.VARCHAR(length=6), nullable=True))
    op.add_column('student', sa.Column('family_head_other', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('student', sa.Column('city_or_village', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('student', sa.Column('family_head_org_membership', mysql.ENUM('nothing', 'member_1_org', 'member_1plus_org', 'office_holder', 'pub_leader'), nullable=True))
    op.add_column('student', sa.Column('earning_fam_members', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('housing_type', mysql.ENUM('hut', 'kacha_house', 'pucca_house', 'kothi'), nullable=True))
    op.add_column('student', sa.Column('owned_items', mysql.VARCHAR(length=1000), nullable=True))
    op.add_column('student', sa.Column('family_head', mysql.ENUM('father', 'mother', 'other'), nullable=True))
    op.drop_column('student', 'whatsapp_number')
    op.drop_column('student', 'religion')
    op.drop_column('student', 'email_id')
    op.drop_column('student', 'current_status')
    # ### end Alembic commands ###
