"""remove mobile column from student table

Revision ID: 4385dfb73d41
Revises: 5ab30371173e
Create Date: 2018-08-14 16:11:00.283388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4385dfb73d41'
down_revision = '5ab30371173e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mobile', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
