"""empty message

Revision ID: 59acf23e72f2
Revises: 4385dfb73d41
Create Date: 2018-08-14 17:18:56.672993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59acf23e72f2'
down_revision = '4385dfb73d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_text', sa.String(length=2000), nullable=True),
    sa.Column('hi_text', sa.String(length=2000), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='testquestiondifficulty'), nullable=False),
    sa.Column('topic', sa.Enum('topic1', 'topic2', 'topic3', 'topic4', name='testquestiontopic'), nullable=False),
    sa.Column('type', sa.Enum('mcq', 'integer_answer', name='testquestiontype'), nullable=False),
    sa.Column('answer', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_text', sa.String(length=2000), nullable=True),
    sa.Column('hi_text', sa.String(length=2000), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrolment_key_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=10), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_key_id'], ['enrolment_keys.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.Enum('rqc', 'interested', 'ekg' , name='incomingcalltype'), nullable=False),
    sa.ForeignKeyConstraint(['contact'], ['student_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outgoing_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact'], ['student_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outgoing_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('test_fail', 'test_pass', 'enrolment_key_gen', 'alg_interview_pass', 'alg_interview_fail', 'other', name='outgoingsmstype'), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['contact'], ['student_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enrolment_keys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('student_contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    op.drop_column('student_contacts', 'created_at')
    op.drop_column('enrolment_keys', 'created_at')
    op.drop_table('outgoing_sms')
    op.drop_table('outgoing_calls')
    op.drop_table('incoming_calls')
    op.drop_table('attempts')
    op.drop_table('question_options')
    op.drop_table('questions')
    # ### end Alembic commands ###
