"""empty message

Revision ID: 61e3ca12a789
Revises: 
Create Date: 2018-02-15 13:15:37.730332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e3ca12a789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrolment_key', sa.String(length=5), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrolment_enrolment_key'), 'enrolment', ['enrolment_key'], unique=True)
    op.create_index(op.f('ix_enrolment_phone_number'), 'enrolment', ['phone_number'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_1', sa.String(length=128), nullable=True),
    sa.Column('option_2', sa.String(length=128), nullable=True),
    sa.Column('option_3', sa.String(length=128), nullable=True),
    sa.Column('option_4', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('en_question_text', sa.String(length=1024), nullable=False),
    sa.Column('hi_question_text', sa.String(length=1024), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'short_answer', 'view', name='questiontype'), nullable=False),
    sa.Column('options_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['options_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_on', sa.DateTime(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=False),
    sa.Column('received_marks', sa.Integer(), nullable=False),
    sa.Column('max_possible_marks', sa.Integer(), nullable=False),
    sa.Column('enrolment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enrolment_id'], ['enrolment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_data')
    op.drop_table('question')
    op.drop_table('options')
    op.drop_index(op.f('ix_enrolment_phone_number'), table_name='enrolment')
    op.drop_index(op.f('ix_enrolment_enrolment_key'), table_name='enrolment')
    op.drop_table('enrolment')
    # ### end Alembic commands ###
