"""empty message

Revision ID: 69625da83c79
Revises: 30c1ecf2bcb4
Create Date: 2018-09-14 17:28:33.363568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69625da83c79'
down_revision = '30c1ecf2bcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_options', sa.Column('correct', sa.Boolean(), nullable=True))
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False))
    op.drop_column('question_options', 'correct')
    # ### end Alembic commands ###
