"""empty message

Revision ID: 7d46ed05464c
Revises: de3da4a4ac0a
Create Date: 2018-03-07 16:37:07.509134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d46ed05464c'
down_revision = 'de3da4a4ac0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'caste_parent_category',
               existing_type=mysql.ENUM('sc', 'st', 'obc', 'general', 'other'),
               nullable=True)
    op.alter_column('student', 'mobile',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('student', 'qualification',
               existing_type=mysql.ENUM('no_reading_writing', 'reading_writing', 'class_5_pass', 'class_8_pass', 'class_10_pass', 'class_12_pass', 'graduate', 'post_graduation', 'prof_degree'),
               nullable=True)
    op.alter_column('student', 'state',
               existing_type=mysql.ENUM('Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'National Capital Territory of Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'),
               nullable=True)
    op.alter_column('student', 'urban_rural',
               existing_type=mysql.ENUM('urban', 'rural'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'urban_rural',
               existing_type=mysql.ENUM('urban', 'rural'),
               nullable=False)
    op.alter_column('student', 'state',
               existing_type=mysql.ENUM('Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'National Capital Territory of Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'),
               nullable=False)
    op.alter_column('student', 'qualification',
               existing_type=mysql.ENUM('no_reading_writing', 'reading_writing', 'class_5_pass', 'class_8_pass', 'class_10_pass', 'class_12_pass', 'graduate', 'post_graduation', 'prof_degree'),
               nullable=False)
    op.alter_column('student', 'mobile',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('student', 'caste_parent_category',
               existing_type=mysql.ENUM('sc', 'st', 'obc', 'general', 'other'),
               nullable=False)
    # ### end Alembic commands ###
