"""empty message

Revision ID: 8bfdde62a78c
Revises: b4a1800fe1a2
Create Date: 2018-08-30 13:30:20.700365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfdde62a78c'
down_revision = 'b4a1800fe1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('answer', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'answer')
    # ### end Alembic commands ###
