"""empty message

Revision ID: 9c862c372602
Revises: 255ece945f0c
Create Date: 2018-08-27 22:05:07.645476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c862c372602'
down_revision = '255ece945f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gender')
    op.drop_column('students', 'dob')
    # ### end Alembic commands ###
