"""empty message

Revision ID: 9f0bc16fe24d
Revises: 8bfdde62a78c
Create Date: 2018-09-04 10:59:27.188181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0bc16fe24d'
down_revision = '8bfdde62a78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('enrolment_keys', sa.Column('question_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrolment_keys', 'sets', ['question_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrolment_keys', type_='foreignkey')
    op.drop_column('enrolment_keys', 'question_set_id')
    op.drop_table('question_order')
    op.drop_table('sets')
    # ### end Alembic commands ###
