"""empty message

Revision ID: b114fad27e5b
Revises: 7d46ed05464c
Create Date: 2018-04-23 14:37:47.940936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b114fad27e5b'
down_revision = '7d46ed05464c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('gl_city_or_village', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('gl_district', sa.String(length=100), nullable=True))
    op.add_column('student', sa.Column('gl_lat', sa.Float(), nullable=True))
    op.add_column('student', sa.Column('gl_long', sa.Float(), nullable=True))
    op.add_column('student', sa.Column('gl_pin_code', sa.String(length=6), nullable=True))
    op.add_column('student', sa.Column('gl_state', sa.Enum('Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'National Capital Territory of Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'gl_state')
    op.drop_column('student', 'gl_pin_code')
    op.drop_column('student', 'gl_long')
    op.drop_column('student', 'gl_lat')
    op.drop_column('student', 'gl_district')
    op.drop_column('student', 'gl_city_or_village')
    # ### end Alembic commands ###
