"""empty message

Revision ID: b4a1800fe1a2
Revises: 7076fe655f84
Create Date: 2018-08-30 04:16:00.070563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a1800fe1a2'
down_revision = '7076fe655f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('selected_option_id', sa.Integer(), nullable=True))
    op.alter_column('attempts', 'enrolment_key_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('attempts', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'attempts', 'question_options', ['selected_option_id'], ['id'])
    op.drop_column('attempts', 'is_correct')
    op.drop_column('attempts', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('answer', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('attempts', sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.alter_column('attempts', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('attempts', 'enrolment_key_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('attempts', 'selected_option_id')
    # ### end Alembic commands ###
