"""empty message

Revision ID: c0f51e9305ef
Revises: 8a8974528c5f
Create Date: 2018-02-17 14:57:30.721613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0f51e9305ef'
down_revision = '8a8974528c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('potential_name', sa.String(length=64), nullable=False))
    op.add_column('student', sa.Column('student_mobile', sa.String(length=10), nullable=False))
    op.drop_column('student', 'phone_number')
    op.drop_column('student', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('student', sa.Column('phone_number', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('student', 'student_mobile')
    op.drop_column('student', 'potential_name')
    # ### end Alembic commands ###
