"""empty message

Revision ID: c1375f5c3918
Revises: 1a6f033e133a
Create Date: 2018-02-14 16:52:22.526059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1375f5c3918'
down_revision = '1a6f033e133a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_phone_number', table_name='enrollment')
    op.create_index(op.f('ix_enrollment_phone_number'), 'enrollment', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_phone_number'), table_name='enrollment')
    op.create_index('ix_enrollment_phone_number', 'enrollment', ['phone_number'], unique=True)
    # ### end Alembic commands ###
