"""empty message

Revision ID: cad2cb0e894b
Revises: f5ffff9eeab3
Create Date: 2018-09-19 14:26:35.332609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad2cb0e894b'
down_revision = 'f5ffff9eeab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrolment_keys', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrolment_keys', 'score')
    # ### end Alembic commands ###
