"""empty message

Revision ID: d4cd80ce729a
Revises: fd29632f91b5
Create Date: 2018-09-17 16:23:53.599051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4cd80ce729a'
down_revision = 'fd29632f91b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('answer_pdf_url', sa.String(length=200), nullable=True))
    op.add_column('sets', sa.Column('question_pdf_url', sa.String(length=200), nullable=True))
    op.drop_column('sets', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.drop_column('sets', 'question_pdf_url')
    op.drop_column('sets', 'answer_pdf_url')
    # ### end Alembic commands ###
