"""Merging more-details & questions endpoints

Revision ID: dee68bda374f
Revises: 78d1bec1c8dc
Create Date: 2018-09-18 08:32:02.481389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dee68bda374f'
down_revision = '78d1bec1c8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_order', sa.Column('answer', sa.String(length=10), nullable=False))
    op.add_column('question_order', sa.Column('enrolment_key_id', sa.Integer(), nullable=True))
    op.add_column('question_order', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.alter_column('question_order', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('question_order_ibfk_2', 'question_order', type_='foreignkey')
    op.create_foreign_key(None, 'question_order', 'enrolment_keys', ['enrolment_key_id'], ['id'])
    op.drop_column('question_order', 'question_order')
    op.drop_column('question_order', 'set_id')
    op.add_column('students', sa.Column('caste', sa.Enum('sc', 'st', 'obc', 'general', 'other', name='caste'), nullable=True))
    op.add_column('students', sa.Column('family_member_income_detail', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('monthly_family_member', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('religion', sa.Enum('hindu', 'muslim', 'christian', 'jain', name='religion'), nullable=True))
    op.add_column('students', sa.Column('total_family_member', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'total_family_member')
    op.drop_column('students', 'religion')
    op.drop_column('students', 'monthly_family_member')
    op.drop_column('students', 'family_member_income_detail')
    op.drop_column('students', 'caste')
    op.add_column('question_order', sa.Column('set_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('question_order', sa.Column('question_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question_order', type_='foreignkey')
    op.create_foreign_key('question_order_ibfk_2', 'question_order', 'sets', ['set_id'], ['id'])
    op.alter_column('question_order', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('question_order', 'is_correct')
    op.drop_column('question_order', 'enrolment_key_id')
    op.drop_column('question_order', 'answer')
    # ### end Alembic commands ###
