"""common text added in question and option

Revision ID: deeffeeaeb0a
Revises: 69625da83c79
Create Date: 2018-09-28 11:52:30.218103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deeffeeaeb0a'
down_revision = '69625da83c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_options', sa.Column('is_common', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('common_text', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'common_text')
    op.drop_column('question_options', 'is_common')
    # ### end Alembic commands ###
