"""empty message

Revision ID: f11a0b9d5c5b
Revises: cad2cb0e894b
Create Date: 2018-09-22 11:36:48.069948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f11a0b9d5c5b'
down_revision = 'cad2cb0e894b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_calls', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_constraint('incoming_calls_ibfk_1', 'incoming_calls', type_='foreignkey')
    op.create_foreign_key(None, 'incoming_calls', 'student_contacts', ['contact_id'], ['id'])
    op.drop_column('incoming_calls', 'contact')
    op.add_column('outgoing_calls', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_constraint('outgoing_calls_ibfk_1', 'outgoing_calls', type_='foreignkey')
    op.create_foreign_key(None, 'outgoing_calls', 'student_contacts', ['contact_id'], ['id'])
    op.drop_column('outgoing_calls', 'contact')
    op.add_column('outgoing_sms', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_constraint('outgoing_sms_ibfk_1', 'outgoing_sms', type_='foreignkey')
    op.create_foreign_key(None, 'outgoing_sms', 'student_contacts', ['contact_id'], ['id'])
    op.drop_column('outgoing_sms', 'contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoing_sms', sa.Column('contact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'outgoing_sms', type_='foreignkey')
    op.create_foreign_key('outgoing_sms_ibfk_1', 'outgoing_sms', 'student_contacts', ['contact'], ['id'])
    op.drop_column('outgoing_sms', 'contact_id')
    op.add_column('outgoing_calls', sa.Column('contact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'outgoing_calls', type_='foreignkey')
    op.create_foreign_key('outgoing_calls_ibfk_1', 'outgoing_calls', 'student_contacts', ['contact'], ['id'])
    op.drop_column('outgoing_calls', 'contact_id')
    op.add_column('incoming_calls', sa.Column('contact', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'incoming_calls', type_='foreignkey')
    op.create_foreign_key('incoming_calls_ibfk_1', 'incoming_calls', 'student_contacts', ['contact'], ['id'])
    op.drop_column('incoming_calls', 'contact_id')
    # ### end Alembic commands ###
