"""Offline Paper Generation

Revision ID: f369aed7b549
Revises: dee68bda374f
Create Date: 2018-09-18 11:04:51.126552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f369aed7b549'
down_revision = 'dee68bda374f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('answer_pdf_url', sa.String(length=200), nullable=True))
    op.add_column('sets', sa.Column('question_pdf_url', sa.String(length=200), nullable=True))
    op.drop_column('sets', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('url', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('sets', 'question_pdf_url')
    op.drop_column('sets', 'answer_pdf_url')
    # ### end Alembic commands ###
