"""empty message

Revision ID: f5ffff9eeab3
Revises: e4be045375f7
Create Date: 2018-09-19 13:32:31.536171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5ffff9eeab3'
down_revision = 'e4be045375f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_order')
    op.add_column('students', sa.Column('monthly_family_income', sa.Integer(), nullable=True))
    op.drop_column('students', 'monthly_family_member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('monthly_family_member', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('students', 'monthly_family_income')
    op.create_table('question_order',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answer', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('enrolment_key_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_correct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['enrolment_key_id'], ['enrolment_keys.id'], name='question_order_ibfk_2'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='question_order_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
